# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
usermod -aG docker vagrant
SCRIPT

Vagrant.configure("2") do |config|


    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    config.vm.box = "ubuntu/xenial64"

    # Share an additional folder to the guest VM. The first argument is
    # the path on the host to the actual folder. The second argument is
    # the path on the guest to mount the folder. And the optional third
    # argument is a set of non-required options.
    config.vm.synced_folder "../commonShare", "/commonShare"

    config.vm.provision "shell" do |s|
        s.path = "../commonShare/get-docker.sh"
    end
    config.vm.provision "shell", inline: $script
    config.vm.provision :reload
end
